### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, I've tried to migrate using v0.14 API.
Could you consider to start using v0.14 API in this plugin?

Please refer to [the upgrading v0.12 to v0.14 guide](http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12) in more details.

**Notice:** This PR contains breaking changes.

Since v0.14, fluentd plugins can handle nanosecond order time precision.

### CODE REVIEW

**Comment by sawanoboly** [comment]
Thanks, looks good to me. How about you @warmfusion ?

I will make the release version 0.10.0 because compatibility will be lost.

**Comment by warmfusion** [comment]
Nice work! I'll need a little time to read through it properly.

As an aside;
The reason for the compatibility with 1.9 is due to selfish reasons - we're still using old debian machines with ruby 1.9 which we're slowly upgrading (300+ servers).

I wonder  if its possible to operate a 0.10 release which requires 0.14.8+ of FluentD (And Ruby 2.1+) and a 0.9.x release which supports ruby 1.9 and fluent < 0.14... maybe a few branches are in order... I'll have a think.

@cosmo0920 - Thanks again; I'll have a read to understand the changes

**Comment by warmfusion** [comment]
This looks very good.

I'll merge it in and make a few administrative changes before releasing (CHANGELOG.md and a required_ruby_version to protect users on older installs (ie myself)

**Comment by cosmo0920** [comment]
Thanks!

**Pull request merged**
