### PR TITLE
Feature/23 - Fix compatibility with Fluent 0.14

### PR DESCRIPTION
**Pull request by warmfusion**
Bumped to 0.9.0 as explicit support for a new minor version of FluentD seemed like a sensible point to bump this plugins minor version too.

* Added support for Fluent 0.14.x
    * travis-ci build validates plugin against fluent 0.10, 0.12 and 0.14
    * Excludes ruby < 2.1 for Fluent 0.14 as fluentd does not support that version
* Compatibility: Use old json library when building for Ruby 1.9 and Fluent <= 0.12
* Added build icon to readme - because I could

### CODE REVIEW

**Comment by warmfusion** [comment]
This Pull request is work in progress - I want to properly validate the functionality works on our live servers before it should be merged

**Comment by sawanoboly** [comment]
Thank you for update 😄  Is there anything I can do ?

**Comment by warmfusion** [comment]
I'm confident the code works - I've hand-patched onto some of my servers and it operates on a ruby 1.9 Fluent 0.12 box as well as ruby 2.2 fluent 0.14

Had some fun with gem trying to update packages it didn't need to, but I believe thats unrelated to this gem but more about other dependencies in the tree having open version requirements causing ruby 1.9 to update to things that simply dont work.

:+1:

**Comment by sawanoboly** [comment]
It's time to merge? Looks like good.

**Comment by sawanoboly** [comment]
OK, Thanks!

`Pushed fluent-plugin-amqp 0.9.0 to rubygems.org.`

**Pull request merged**
