### PR TITLE
Add automatic failover support for multiple hosts on same cluster

### PR DESCRIPTION
**Pull request by warmfusion**
As shown in the updated Readme, this patch allows for multiple hosts to be given to the configuration such that the bunny library will automatically reconnect to a cluster of servers without requiring additional load balancers (and the associated confusion caused by their appearing to be 'online')

Also added myself as an Author ;-)

### CODE REVIEW

**Comment by sawanoboly** [comment]
I see what you mean. https://github.com/ruby-amqp/bunny/blob/86f6da6197a43f87497daaed16fdd42148bc1407/lib/bunny/session.rb#L97-L98

It's good feature.

> Also added myself as an Author ;-)

Thank you!

**Comment by sawanoboly** [comment]
v0.8.0 had been released.

**Comment by sawanoboly** [comment]
@warmfusion If you like, I'll add you to collaborators of this repo? 

I've not using this plugin for currently, although it might use in the future.

**Comment by warmfusion** [comment]
Sounds good to me - but I'll maintain the pull request model going on, I'm not going to start merging my own stuff into master without peer review.

For reference; I'm using the plugin on ~300 hosts, writing about 1,000 messages a second all day long on a mix of ruby 1 and ruby 2 servers...

**Comment by sawanoboly** [comment]
OK. I'll maintain the status quo.

**Pull request merged**
