### PR TITLE
Adding coverage support

### PR DESCRIPTION
**Pull request by warmfusion**
Thinking about setting up code-climate for this repo

### CODE REVIEW

**Comment by warmfusion** [comment]
Someone who's an `owner` on this repository needs to goto here - https://lima.codeclimate.com/github/giraffi/fluent-plugin-amqp

and find out what the REPO_TOKEN is so the above change can had the right token applied.

Or give me owner rights for a little while and I'll set it up :-)

**Comment by sawanoboly** [comment]
Ok, I'll check how to enable it.

**Comment by sawanoboly** [comment]
I've added https://codeclimate.com/github/giraffi/fluent-plugin-amqp as open source project.
And, according to GIthub's help,  Open Source project unfortunately we don't yet support service hooks for these repositories.

Can I merge this branch to check ?

**Comment by warmfusion** [comment]
Not sure what the service hooks are needed for, and merging in at the moment may cause the build to fail. But why not.

**Pull request merged**
