### PR TITLE
Support header configuration on events - Fixes #35

### LINKED ISSUE #35: Provide a way to specify headers from the message
It would be nice if there were a way to set headers for a message based on the contents of the message. For example, if we have messages that look like the following (taken from [the parser plugin docs](http://docs.fluentd.org/articles/parser-plugin-overview):
```
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"INFO","message":"  Main - Start"}
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"ERROR","message":" Main - Exception\njavax.management.RuntimeErrorException: null\n    at Main.main(Main.java:16) ~[bin/:na]"}
2013-03-03 14:27:33 +0900 zimbra.mailbox: {"thread":"main","level":"INFO","message":"  Main - End"}
```
It would be nice to be able to set a header on the message when sent to RabbitMQ whose value is the that of the `level` field, maybe by doing something like this:
```
<match **>
  type amqp
  exchange amq.headers
  host amqp.example.com
  port 5672
  vhost /
  user guest
  pass guest
  format json
  <header>
    name LogLevel
    source level
    default "INFO"
  </header>
</match>
```
This would make it possible to use Headers exchanges properly.

### PR DESCRIPTION
**Pull request by warmfusion**
Note: This'll have a merge conflict with #39 as Ive refactored tests and changelogs etc.

Plugin now supports multiple headers to be defined on input using the new `header` configuration section.

See the modified Readme and test cases for how this works in practice.

This fixes #35

### CODE REVIEW

**Comment by elyscape** [comment]
[Here's a somewhat simpler version I wrote](https://github.com/elyscape/fluent-plugin-amqp/commit/4d08f7f36d54de1eef9ffc5afc13ccc75dfc634c), which also supports setting the source to nested fields. It might be worthwhile to incorporate that functionality. I didn't submit it as a pull request because I based it on an old version of the plugin for Fluentd 0.12 support.

**Comment by warmfusion** [comment]
I like the use of a list of headers, first one winning. I'm not sure I see how that supports sub-keys though. 

I'll incorporate your use of the loop, but will move the header processing into the HeaderElement class so that it's more decoupled; and may allow for ruby blocks to be passed into the config in the future.

**Comment by elyscape** [comment]
The part that handles subkeys is this part:
```ruby
if header.path
  temp_data = data
  temp_path = header.path.dup
  until temp_data.nil? or temp_path.empty?
    temp_data = temp_data[temp_path.shift]
  end
  header_val = temp_data if temp_data
end
```
The `path` parameter is a list of key names. This part:
```ruby
until temp_data.nil? or temp_path.empty?
  temp_data = temp_data[temp_path.shift]
end
```
removes the first element from `temp_path`, retrieves the member of `temp_data` with that key, and replaces `temp_data` with it, effectively walking the structure. As an example:

|Loop iteration|temp_data|temp_path|
|-|-|-|
|0|`{'a'=>{'b'=>{'c'=>'d'}}}`|`['a', 'b', 'c']`|
|1|`{'b'=>{'c'=>'d'}}`|`['b', 'c']`|
|2|`{'c'=>'d'}`|`['c']`|
|3|`'d'`|`[]`|

At which point the loop exits and `'d'` is returned.

As an aside, the last line should probably be changed to this to avoid potential false negatives:
```ruby
header_val = temp_data unless temp_data.nil?
```

**Comment by warmfusion** [comment]
Oh of course. I saw the shift but was thinking it was a pop. That's fine. 😀

Also means that while the idea of multiple headers is real, it isn't what you're code was doing at all. 

Glad I write tests.

**Comment by warmfusion** [comment]
Righty - I think this'll do the job...

You can set headers, set them multiple times, set defaults, fallbacks, get nested keys, and its all tested through rake - Though I've not actually tried it in anger on a real deployment...

Coverage of the output plugin is at 98% (including a few bits ive chosen to ignore due to untestability)

**Pull request merged**
